inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/PredicatePrefix:
  ForbiddenPrefixes:
    - is_

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/RedundantPercentQ:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - qiita-markdown.gemspec
    - spec/**/*
