inherit_from: .rubocop_todo.yml

Metrics/ClassLength:
  Enabled: false

Style/AsciiComments:
  Exclude:
    - benchmark/**/*

Style/EmptyCaseCondition:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/UnneededPercentQ:
  Enabled: false
