name: Test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-18.04', 'macos-latest']
        ruby: ['2.2', '2.3', '2.4', '2.5', '2.7']
        experimental: [false]
        include:
          - os: 'ubuntu-18.04'
            ruby: 'head'
            experimental: true
        exclude:
          - os: 'ubuntu-18.04'
            ruby: '2.2'
          - os: 'ubuntu-18.04'
            ruby: '2.3'
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CC_TEST_REPORTER_ID }}
          GITHUB_BRANCH: ${{ steps.branch-name.outputs.current_branch }}
